services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server-test
    command: npm run test
    environment:
      - NODE_ENV=test
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=test_password
      - DATABASE_PORT=5432
    depends_on:
      - postgres
    networks:
      - retrolist-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - retrolist-network

networks:
  retrolist-network:
    driver: bridge
