services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server-production
    working_dir: /app/apps/server
    command: node dist/app.js
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=5432
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - retrolist-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - retrolist-network

networks:
  retrolist-network:
    driver: bridge
