version: "3.8"

services:
  shared:
    build:
      context: ../..
      dockerfile: packages/shared/Dockerfile
    volumes:
      - ../../packages/shared:/usr/src/app
    networks:
      - retrolist-network

  server:
    build:
      context: ../..
      dockerfile: apps/server/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DATABASE_URL=postgres
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=5432
    depends_on:
      - postgres
      - shared
    volumes:
      - ../../packages/shared:/usr/src/app/packages/shared
    networks:
      - retrolist-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/seed:/docker-entrypoint-initdb.d/seed
    networks:
      - retrolist-network

networks:
  retrolist-network:
    driver: bridge
