/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface HandheldDevices {
  analogs_raw: string | null;
  aspect_ratio: string;
  audio_output_raw: string | null;
  battery_capacity: string;
  brand: string;
  charge_port_raw: string;
  chipset: string | null;
  color_options: string;
  connectivity_raw: string | null;
  cooling_raw: string | null;
  cpu_arch: string | null;
  cpu_clock: string | null;
  cpu_cores: string | null;
  cpu_model: string | null;
  cpu_threads: string | null;
  device_name: string;
  dimensions_mm: string | null;
  dpad_raw: string;
  dreamcast: number;
  emulation_desc: string | null;
  extra_buttons_raw: string | null;
  face_buttons: string;
  form_factor: string;
  gba: number;
  gbc: number;
  genesis: number;
  gpu_clock: string | null;
  gpu_cores: string | null;
  gpu_model: string | null;
  has_analog_triggers: boolean;
  has_analogs: boolean;
  has_audio_output: boolean;
  has_bt: boolean;
  has_cooling: boolean | null;
  has_dual_analogs: boolean;
  has_dual_external_sd: boolean;
  has_hall_analogs: boolean;
  has_l2_r2: boolean;
  has_l3_r3: boolean;
  has_lte: boolean;
  has_rumble: boolean | null;
  has_shoulder_buttons: boolean;
  has_thunderbolt: boolean;
  has_usb_otg: boolean;
  has_video_output: boolean | null;
  has_wifi: boolean;
  id: string;
  image_id: string;
  n3ds: number;
  n64: number;
  nds: number;
  nes: number;
  ngc: number;
  os_raw: string;
  ppi: Numeric;
  price_high: Numeric | null;
  price_low: Numeric;
  ps2: number;
  ps3: number;
  psp: number;
  psx: number;
  ram_gb: string | null;
  release_date: Timestamp;
  resolution: string;
  reviews: string | null;
  saturn: number;
  screen_lens: string | null;
  screen_size_inches: Numeric;
  screen_type: string;
  sensors_raw: string | null;
  shell_material: string;
  shoulder_buttons_raw: string | null;
  snes: number;
  speaker_raw: string | null;
  storage_raw: string;
  switch: number;
  video_output_raw: string | null;
  volume_desc: string | null;
  weight_g: number | null;
  wii: number;
  wiiu: number;
}

export interface DB {
  handheld_devices: HandheldDevices;
}
