name: Test Server Docker Compose

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-tests-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build and run tests
        run: |
          docker-compose -f "docker-compose.test.yml" up --build --exit-code-from server
        continue-on-error: true

      - name: Cleanup
        if: always()
        run: docker-compose -f "docker-compose.test.yml" down -v
