name: Test Server Docker Compose

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-tests-docker-compose:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Run Docker Compose and Test Server
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.test.yml
          up-flags: --build --exit-code-from server
          down-flags: --remove-orphans

      - name: Cleanup
        if: always()
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: docker-compose.test.yml
          down-flags: --remove-orphans
